### ISSUE TITLE
Block missing

### ISSUE THREAD

**Issue by Alhamzi** [andreviniciusgsg/gr-macprotocols#1]
Hallo
i tried to install the module but at the end I got the following error 

adnan@adnan-X555LJ:~/gr-macprotocols/build$ grcc ../examples/cs.grc
Block key "macprotocols_cs" not found
Validation failed:

Block - blocks_vector_to_stream_0 - Vector to Stream(blocks_vector_to_stream):
	Source - out(0):
		Port is not connected.

Block - pad_sink_0 - Pad Sink(pad_sink):
	Sink - in(in):
		Port is not connected.

Block - pad_source_0_0 - Pad Source(pad_source):
	Source - out(out):
		Port is not connected.
Error during file compilation

Also I installed gr-ieee802.11. It works successfully. Could you please help me ?
thanks in advance

**Comment by gom3sa** [comment]
Hi! There was an error in the instructions for installing gr-toolkit. If you just copied/ pasted the commands, you probably missed it out. The module did not build since it had no "cd build" after creating the "build" directory. I corrected it and I also uploaded an installation script to make things easier. Check **install_gr-macprotocols.sh** out. It works as far as I'm concerned.
